blank_issues_enabled: true
contact_links:
  - name: Las aplicaciones / The apps
    url: https://boriken.dev/
    about: Qué hacen, cómo se usan, y sus políticas de privacidad.
  - name: Algo privado / Something private
    url: mailto:cacique@boriken.dev
    about: Para lo que no quieras publicar, incluyendo un problema de seguridad.
